spring:
  # ZIPKIN PROPERTIES
#  sleuth:
#  zipkin:
#    baseUrl: http://tracing-server:9411  

  # ADMIN PROPERTIES
  boot:
    admin:
      client:
        url: http://localhost:9090

        
# DISCOVERY SERVER PROPERTIES
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

petclinic:
  database:
    host: localhost:3306