# start services on random port by default
server:
  port: 0

spring:
  # DATABASE PROPERTIES
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: validate
  
  # DATABASE PROPERTIES
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_clinic?serverTimezone=Europe/Madrid&useSSL=false
    username: root
    password: admin
  
  # ZIPKIN PROPERTIES
  sleuth:
    sampler:
#      probability: 1.0
      percentage: 1.0
#  zipkin:
#    baseUrl: http://tracing-server:9411  

  # ADMIN PROPERTIES
  boot:
    admin:
      client:
        url: http://localhost:9090

  cloud:
    config:
       # Allow the microservices to override the remote properties with their own System properties or config file
       allow-override: true
       # Override configuration with any local property source
       override-none: true
    # Temporary hack required by the Spring Boot 2 / Spring Cloud Finchley branch
    # Waiting issue https://github.com/spring-projects/spring-boot/issues/13042
    refresh:
      refreshable: false
        
# DISCOVERY SERVER PROPERTIES
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    #instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
# ACTUATOR PROPERTIES
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
  metrics:
    export:
      prometheus:
        enabled: true
